### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by dmeijboom**

### CODE REVIEW

**Comment by dmeijboom** [comment]
We're going to use the `python3` branch

**Comment by kerrermanisNL** [comment]
Don't know what branch this was about, but think this is worth opening still. The other3 python repo seems to not have setup.py in the correct location

**Comment by dmeijboom** [comment]
> Don't know what branch this was about, but think this is worth opening still. The other3 python repo seems to not have setup.py in the correct location

Yes, finally merged :laughing:

**Comment by kerrermanisNL** [comment]
Haha :sweat_smile:

**Pull request merged**
